### ISSUE TITLE
[FR]: Transfert attachments alongside the files

### ISSUE THREAD

**Issue by Lisandra-dev** [ImaginaryProgramming/obsidian-vault-transfer#5]
I have a lot of note I want to transfert into my Archive vault, and want to know if their attachment will be transfered too!
If not, can you add this possibility ?

**Comment by ImaginaryProgramming** [comment]
Good idea! I hadn't thought about attachments. It's not supported at the moment, although it might be possible.

**Comment by ImaginaryProgramming** [comment]
Good to know, thank you! I'll see if I can get anywhere with that next time I work on the plugin.
