### ISSUE TITLE
Attachments?

### ISSUE THREAD

**Issue by dahifi** [ImaginaryProgramming/obsidian-vault-transfer#8]
Before I install this I wanted to inquire whether it also transfers any attachments? I have a number of linked images and recordings that I reference in one of my project folders, and I'd like to transfer them all (or at least make a copy).

**Comment by ImaginaryProgramming** [comment]
It does support transferring attachments thanks to #6, but I forgot to make a release with those improvements. The version after 1.1.0 will have them.

I've tested it a bit and haven't had issues, but the plugin isn't super mature yet, so I'd recommend having backups of some sort before you transfer non-image attachments.

**Comment by ImaginaryProgramming** [comment]
This has been in for a while now, so closing the issue.
