### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by adrianomarqui** [ImaginaryProgramming/obsidian-vault-transfer#9]
How to install this plugin?

**Comment by ImaginaryProgramming** [comment]
I'm working on getting it added to the normal Community Plugins list in Obsidian, but for the meantime [this video](https://www.youtube.com/watch?v=ffGfVBLDI_0) may help.

**Comment by adrianomarqui** [comment]
> I'm working on getting it added to the normal Community Plugins list in Obsidian, but for the meantime [this video](https://www.youtube.com/watch?v=ffGfVBLDI_0) may help.

Thanks a lot. Best work

**Comment by ImaginaryProgramming** [comment]
It's now in the community plugins, so it should be possible to install through that just by searching for "Vault Transfer".
